'use strict';
const canvas=document.querySelector('#space'),ctx=canvas.getContext('2d'),world=new OrbitWorld();
const palette=['#a9b9ff','#ffb39d','#86e1ce','#ddafff','#ffd68c','#8dccff'];
let paused=false,trails=true,kind='planet',mode='launch',scene='solar',zoom=1,width=900,height=650,scale=1,drag=null,dirty=false,mission=null,toastTimer,previous=0,accumulator=0,trailClock=0;
const camera={x:0,y:0},touches=new Map();let pan=null,gesture=null,multiTouch=false,spaceHeld=false,spaceUsed=false;
const stars=Array.from({length:145},(_,n)=>({x:((n*4217+331)%10007)/10007,y:((n*2767+173)%9973)/9973,r:n%11===0?1.35:.65,a:.15+(n%7)/16}));
const $=s=>document.querySelector(s);
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600);}
function options(){const value=Number($('#mass').value);return{kind,mass:kind==='star'?value*500:kind==='asteroid'?value*.25:value*2,color:kind==='star'?'#ffd18a':kind==='asteroid'?'#a0b4c1':palette[world.nextId%palette.length]};}
function updateMass(){$('#mass-value').textContent=String(options().mass);}
$('#mass').addEventListener('input',updateMass);updateMass();
for(const b of document.querySelectorAll('[data-kind]'))b.addEventListener('click',()=>{kind=b.dataset.kind;for(const other of document.querySelectorAll('[data-kind]'))other.setAttribute('aria-pressed',other===b);updateMass();});
function cursor(){canvas.style.cursor=pan||gesture?'grabbing':mode==='pan'||spaceHeld?'grab':'crosshair';}
function setMode(value){mode=value;drag=null;for(const name of ['launch','orbit','pan'])$('#'+name).setAttribute('aria-pressed',value===name);$('#mode-tip').textContent=value==='launch'?'从起点拖向终点，拖得越长，速度越快。':value==='orbit'?'在恒星旁点击，自动给它一个环绕速度。':'按住拖动浏览宇宙，不会放置或删除天体。';$('#canvas-help').textContent=value==='launch'?'左键拖拽发射 · 右键拖拽移动画面 · 双指平移缩放':value==='orbit'?'点击放置环绕星球 · 右键拖拽移动画面':'按住并拖动移动画面 · 滚轮或双指缩放 · 全景找回星系';cursor();}
for(const name of ['launch','orbit','pan'])$('#'+name).addEventListener('click',()=>setMode(name));
function setPause(value){paused=value;$('#pause').textContent=value?'继续':'暂停';$('#pause').setAttribute('aria-pressed',value);accumulator=0;}
$('#pause').addEventListener('click',()=>setPause(!paused));
$('#trails').addEventListener('click',()=>{trails=!trails;$('#trails').textContent=trails?'轨迹：开':'轨迹：关';$('#trails').setAttribute('aria-pressed',trails);});
$('#speed').addEventListener('input',()=>$('#speed-value').textContent=`${Number($('#speed').value)}×`);
function loadScene(value,initial=false){if(dirty&&!initial&&!window.confirm('切换场景会替换你放置的星球，继续吗？'))return false;world.preset(value);scene=value;dirty=false;mission=null;drag=null;pan=null;gesture=null;touches.clear();multiTouch=false;camera.x=camera.y=0;zoom=1;setPause(false);$('#scene-title').textContent={solar:'一个小太阳系',binary:'双星之舞',collision:'碰撞实验',empty:'等待第一颗星'}[value];for(const b of document.querySelectorAll('[data-scene]'))b.setAttribute('aria-pressed',b.dataset.scene===value);$('#mission').textContent=value==='empty'?'先放一颗恒星，再为它添加环绕的行星。':'发射一颗行星，让它稳定绕行 20 秒。';resize();cursor();return true;}
for(const b of document.querySelectorAll('[data-scene]'))b.addEventListener('click',()=>loadScene(b.dataset.scene));$('#reset').addEventListener('click',()=>loadScene(scene));
function resize(){const rect=canvas.getBoundingClientRect();width=rect.width;height=rect.height;const ratio=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);scale=Math.min(width/1100,height/880)*zoom;}
new ResizeObserver(resize).observe(canvas);
function setZoom(value){zoom=Math.max(.05,Math.min(4,value));scale=Math.min(width/1100,height/880)*zoom;}
$('#zoom-in').addEventListener('click',()=>setZoom(zoom*1.25));$('#zoom-out').addEventListener('click',()=>setZoom(zoom/1.25));
$('#fit').addEventListener('click',()=>{if(!world.bodies.length){camera.x=camera.y=0;setZoom(1);return;}const left=Math.min(...world.bodies.map(b=>b.x-b.radius)),right=Math.max(...world.bodies.map(b=>b.x+b.radius)),top=Math.min(...world.bodies.map(b=>b.y-b.radius)),bottom=Math.max(...world.bodies.map(b=>b.y+b.radius));camera.x=(left+right)/2;camera.y=(top+bottom)/2;setZoom(Math.min(width/(right-left+140),height/(bottom-top+140))/Math.min(width/1100,height/880));});
function zoomAt(value,p){const before=toWorld(p);setZoom(value);const after=toWorld(p);camera.x+=before.x-after.x;camera.y+=before.y-after.y;}
canvas.addEventListener('wheel',e=>{e.preventDefault();if(!drag)zoomAt(zoom*(e.deltaY<0?1.1:1/1.1),e);},{passive:false});
function toWorld(e){const rect=canvas.getBoundingClientRect();return{x:(e.clientX-rect.left-width/2)/scale+camera.x,y:(e.clientY-rect.top-height/2)/scale+camera.y};}
function beginMission(b){const anchor=world.bodies.filter(a=>a.kind==='star'&&a.id!==b.id).sort((a,c)=>c.mass-a.mass)[0];if(b.kind!=='planet'||!anchor)return;const dx=b.x-anchor.x,dy=b.y-anchor.y;mission={id:b.id,anchor:anchor.id,start:world.time,radius:Math.hypot(dx,dy),lastAngle:Math.atan2(dy,dx),angle:0,state:'running'};$('#mission').textContent='观察你的行星：保持环绕 20 秒。';}
function addBody(input,automatic=false){let b;try{b=automatic?world.orbit(input.x,input.y,{...options(),...input}):world.add({...options(),...input});}catch(error){toast(error.message);return null;}dirty=true;beginMission(b);if(paused)toast('星球已放好，点击「继续」让时间流动。');return b;}
function removeAt(p){let closest=null,distance=Infinity;for(const b of world.bodies){const d=Math.hypot(p.x-b.x,p.y-b.y);if(d<Math.max(b.radius,14/scale)&&d<distance){closest=b;distance=d;}}if(closest){world.bodies=world.bodies.filter(b=>b.id!==closest.id);dirty=true;toast('已移除这颗天体');}}
function touchMetrics(){const [a,b]=Array.from(touches.values());return{x:(a.x+b.x)/2,y:(a.y+b.y)/2,distance:Math.max(1,Math.hypot(a.x-b.x,a.y-b.y))};}
canvas.addEventListener('pointerdown',e=>{if(![0,1,2].includes(e.button))return;e.preventDefault();canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);
  if(e.pointerType==='touch'){touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size>=2){multiTouch=true;drag=null;pan=null;gesture=touchMetrics();cursor();return;}if(multiTouch)return;}
  if(e.button===2||e.button===1||spaceHeld||mode==='pan'){if(spaceHeld)spaceUsed=true;pan={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false,canDelete:e.button===2&&mode!=='pan'&&!spaceHeld};drag=null;cursor();return;}
  const p=toWorld(e);drag={id:e.pointerId,start:p,end:p,mode};accumulator=0;
});
canvas.addEventListener('pointermove',e=>{if(touches.has(e.pointerId))touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(multiTouch){if(touches.size>=2&&gesture){const current=touchMetrics();camera.x-=(current.x-gesture.x)/scale;camera.y-=(current.y-gesture.y)/scale;zoomAt(zoom*current.distance/gesture.distance,{clientX:current.x,clientY:current.y});gesture=current;}return;}
  if(pan&&pan.id===e.pointerId){if(Math.hypot(e.clientX-pan.startX,e.clientY-pan.startY)>4||pan.moved){pan.moved=true;camera.x-=(e.clientX-pan.x)/scale;camera.y-=(e.clientY-pan.y)/scale;pan.x=e.clientX;pan.y=e.clientY;}return;}if(drag&&e.pointerId===drag.id)drag.end=toWorld(e);
});
function finishPointer(e,cancel=false){touches.delete(e.pointerId);if(multiTouch){if(touches.size<2)gesture=null;if(touches.size===0)multiTouch=false;drag=null;pan=null;cursor();return;}
  if(pan?.id===e.pointerId){const p=pan;pan=null;if(!cancel&&!p.moved&&p.canDelete)removeAt(toWorld(e));cursor();return;}
  if(drag?.id!==e.pointerId)return;const d=drag;drag=null;if(!cancel){const p=toWorld(e);if(d.mode==='orbit')addBody(p,true);else addBody({x:d.start.x,y:d.start.y,vx:(p.x-d.start.x)*.35,vy:(p.y-d.start.y)*.35});}cursor();
}
canvas.addEventListener('pointerup',e=>finishPointer(e));canvas.addEventListener('pointercancel',e=>finishPointer(e,true));canvas.addEventListener('lostpointercapture',e=>finishPointer(e,true));canvas.addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.matches('input,button,textarea,select,a'))return;if(e.code==='Space'){e.preventDefault();if(!spaceHeld){spaceHeld=true;spaceUsed=false;cursor();}}if(e.code==='Escape'){drag=null;pan=null;cursor();}});
window.addEventListener('keyup',e=>{if(e.code==='Space'&&spaceHeld){e.preventDefault();spaceHeld=false;if(!spaceUsed)setPause(!paused);cursor();}});
window.addEventListener('blur',()=>{spaceHeld=false;spaceUsed=false;drag=null;pan=null;gesture=null;touches.clear();multiTouch=false;cursor();});
function updateMission(){if(!mission||mission.state!=='running')return;const b=world.bodies.find(b=>b.id===mission.id),anchor=world.bodies.find(b=>b.id===mission.anchor);if(!b||!anchor){mission.state='failed';$('#mission').textContent='轨道中断了，再发射一颗试试。';return;}const dx=b.x-anchor.x,dy=b.y-anchor.y,r=Math.hypot(dx,dy),angle=Math.atan2(dy,dx);let delta=angle-mission.lastAngle;if(delta>Math.PI)delta-=2*Math.PI;if(delta< -Math.PI)delta+=2*Math.PI;mission.angle+=Math.abs(delta);mission.lastAngle=angle;const age=world.time-mission.start;
  if(r>mission.radius*1.7||r<mission.radius*.55){mission.state='failed';$('#mission').textContent='轨道偏离太多了。换个速度，或试试一键环绕。';return;}
  if(age>=20){mission.state=mission.angle>.5?'won':'failed';$('#mission').textContent=mission.state==='won'?'成功！你的小行星已经稳定绕行 20 秒。':'它还没有绕起来，给它一点横向速度吧。';if(mission.state==='won')toast('小挑战完成：稳定环绕 20 秒');}
  else $('#mission').textContent=`你的行星已坚持 ${Math.floor(age)} / 20 秒${age>8?'，继续观察。':'。'}`;
}
function dot(x,y,r,color){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
function render(){ctx.fillStyle='#090f23';ctx.fillRect(0,0,width,height);for(const s of stars){ctx.globalAlpha=s.a;dot(s.x*width,s.y*height,s.r,'#ccdbff');}ctx.globalAlpha=1;
  ctx.save();ctx.translate(width/2-camera.x*scale,height/2-camera.y*scale);ctx.scale(scale,scale);
  if(scene==='solar'){ctx.strokeStyle='#7c93d011';ctx.lineWidth=1/scale;ctx.setLineDash([3/scale,7/scale]);for(const r of [110,190,285,385]){ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.stroke();}ctx.setLineDash([]);}
  if(trails)for(const b of world.bodies){if(b.trail.length<2)continue;ctx.beginPath();b.trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle=b.color;ctx.lineWidth=1.3/scale;ctx.globalAlpha=.5;ctx.stroke();}ctx.globalAlpha=1;
  for(const e of world.events){ctx.beginPath();ctx.arc(e.x,e.y,e.radius+e.age*85,0,Math.PI*2);ctx.strokeStyle=e.color;ctx.globalAlpha=Math.max(0,1-e.age/1.5);ctx.lineWidth=2/scale;ctx.stroke();}ctx.globalAlpha=1;
  for(const b of world.bodies){const halo=b.kind==='star'?b.radius*4:b.radius*2.5,glow=ctx.createRadialGradient(b.x,b.y,0,b.x,b.y,halo);glow.addColorStop(0,b.color+(b.kind==='star'?'70':'30'));glow.addColorStop(1,b.color+'00');dot(b.x,b.y,halo,glow);dot(b.x,b.y,b.radius,b.color);dot(b.x-b.radius*.28,b.y-b.radius*.28,b.radius*.34,'#ffffff50');if(b.fixed){ctx.strokeStyle='#ffd18a66';ctx.lineWidth=1/scale;ctx.beginPath();ctx.arc(b.x,b.y,b.radius+5/scale,0,Math.PI*2);ctx.stroke();}}
  if(drag&&drag.mode==='launch'){const start=drag.start,end=drag.end,vx=(end.x-start.x)*.35,vy=(end.y-start.y)*.35;let px=start.x,py=start.y,pvx=vx,pvy=vy;ctx.beginPath();ctx.moveTo(px,py);for(let n=0;n<110;n++){let ax=0,ay=0;for(const b of world.bodies){const dx=b.x-px,dy=b.y-py,d2=dx*dx+dy*dy+36;ax+=60*b.mass*dx/(d2*Math.sqrt(d2));ay+=60*b.mass*dy/(d2*Math.sqrt(d2));}pvx+=ax*.035;pvy+=ay*.035;px+=pvx*.035;py+=pvy*.035;ctx.lineTo(px,py);}ctx.setLineDash([4/scale,6/scale]);ctx.strokeStyle='#bbc8ff66';ctx.lineWidth=1.5/scale;ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(start.x,start.y);ctx.lineTo(end.x,end.y);ctx.strokeStyle='#e1e7ff';ctx.lineWidth=1.5/scale;ctx.stroke();const angle=Math.atan2(end.y-start.y,end.x-start.x);if(Math.hypot(end.x-start.x,end.y-start.y)>3){ctx.beginPath();ctx.moveTo(end.x-12/scale*Math.cos(angle-.45),end.y-12/scale*Math.sin(angle-.45));ctx.lineTo(end.x,end.y);ctx.lineTo(end.x-12/scale*Math.cos(angle+.45),end.y-12/scale*Math.sin(angle+.45));ctx.stroke();}dot(start.x,start.y,6/scale,'#c3ceff');}
  ctx.restore();$('#body-count').textContent=String(world.bodies.length);$('#collision-count').textContent=`${world.collisions} 次碰撞`;$('#elapsed').textContent=`${Math.floor(world.time)} 秒`;}
function frame(now){const dt=previous?Math.min(.05,(now-previous)/1000):0;previous=now;if(!paused&&!drag){accumulator+=dt*Number($('#speed').value);let n=0;while(accumulator>=1/120&&n<24){world.step(1/120);accumulator-=1/120;trailClock+=1/120;if(trailClock>=.035){world.recordTrails();trailClock=0;}n++;}updateMission();}render();requestAnimationFrame(frame);}
loadScene('solar',true);setMode('launch');requestAnimationFrame(frame);

// Optional browser tools use the same actions as the visible controls.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'read_orbit_state',description:'Read the current gravity toy scene and bodies.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{},additionalProperties:false},execute(){return{scene,paused,time:world.time,collisions:world.collisions,bodies:world.bodies.map(({id,x,y,vx,vy,mass,kind})=>({id,x,y,vx,vy,mass,kind}))};}});
  register({name:'add_orbit_body',description:'Add a body using the same launch or orbit action as the canvas.',annotations:{readOnlyHint:false},inputSchema:{type:'object',properties:{x:{type:'number'},y:{type:'number'},vx:{type:'number'},vy:{type:'number'},mass:{type:'number',minimum:1,maximum:40000},kind:{enum:['planet','star','asteroid']},orbit:{type:'boolean'}},required:['x','y'],additionalProperties:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['x','y','vx','vy','mass','kind','orbit'].includes(k))||!['x','y'].every(k=>Number.isFinite(input[k]))||['vx','vy','mass'].some(k=>input[k]!==undefined&&!Number.isFinite(input[k]))||(input.mass!==undefined&&(input.mass<1||input.mass>40000))||(input.kind!==undefined&&!['planet','star','asteroid'].includes(input.kind))||(input.orbit!==undefined&&typeof input.orbit!=='boolean'))throw new Error('无效的天体参数');const {orbit,...body}=input;const b=addBody(body,orbit===true);if(!b)throw new Error('无法放置天体');render();return{id:b.id,kind:b.kind,mass:b.mass};}});
}

