'use client';
import { useMemo, useRef, useState } from 'react';
import { BarChart3, LineChart, PieChart, Download, FileText, RotateCcw, Palette, Table2 } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Pick, download } from './shared';
import { parseTable, numberValue, ParsedTable } from '@/lib/studio-model';
import { useWebTool } from './web-tools';
const sample = '月份\t收入\t支出\n一月\t4200\t2600\n二月\t3800\t2400\n三月\t5100\t3200\n四月\t4600\t2800\n五月\t6200\t3600\n六月\t5800\t3100';
const palettes = {
  report: { name: '清爽报告', bg: '#ffffff', ink: '#192f50', grid: '#e5edf5', colors: ['#4676e8', '#719beb', '#2cbbc0', '#9c7ee0', '#eab95a', '#ed8698'], font: 'Arial, Microsoft YaHei, sans-serif' },
  academic: { name: '学术蓝', bg: '#fcfcfd', ink: '#222f43', grid: '#e1e5eb', colors: ['#244d74', '#6097a7', '#a6bdce', '#66718b', '#b4a690', '#829976'], font: 'Georgia, Microsoft YaHei, serif' },
  poster: { name: '夜色海报', bg: '#182438', ink: '#e8f1ff', grid: '#344256', colors: ['#bce686', '#6bd3da', '#f6c97d', '#a9a3e8', '#ef96a5', '#89b6ee'], font: 'Arial, Microsoft YaHei, sans-serif' },
};
type Theme = keyof typeof palettes; type ChartType = 'bar' | 'line' | 'pie';
const short = (s: string, n = 16) => s.length > n ? s.slice(0, n - 1) + '…' : s;
const format = (n: number) => new Intl.NumberFormat('zh-CN', { maximumFractionDigits: 2, notation: Math.abs(n) >= 100000 ? 'compact' : 'standard' }).format(n);
function ticks(values: number[]) { let lo = Math.min(0, ...values), hi = Math.max(0, ...values); if (lo === hi) hi = lo + 1; const raw = (hi - lo) / 5, power = 10 ** Math.floor(Math.log10(raw)), step = [1, 2, 2.5, 5, 10].find(n => n * power >= raw)! * power; lo = Math.floor(lo / step) * step; hi = Math.ceil(hi / step) * step; return { lo, hi, values: Array.from({ length: Math.round((hi - lo) / step) + 1 }, (_, i) => lo + i * step) }; }
function Chart({ table, xcol, ycol, type, theme, title, subtitle, unit, source, svgRef }: { table: ParsedTable; xcol: number; ycol: number; type: ChartType; theme: Theme; title: string; subtitle: string; unit: string; source: string; svgRef: React.RefObject<SVGSVGElement | null> }) {
  const p = palettes[theme], vals = table.rows.map(r => numberValue(r[ycol])!), labels = table.rows.map(r => r[xcol]);
  const scale = ticks(vals), left = 95, right = 925, top = 140, bottom = 485, chartWidth = right - left, chartHeight = bottom - top;
  const y = (v: number) => bottom - (v - scale.lo) / (scale.hi - scale.lo) * chartHeight;
  const sum = vals.reduce((a, b) => a + b, 0); let angle = -Math.PI / 2;
  return <svg ref={svgRef} className="chart-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 640" role="img" aria-label={`${title}，${table.headers[ycol]}${type === 'bar' ? '柱状图' : type === 'line' ? '折线图' : '占比图'}`} style={{ fontFamily: p.font }}>
    <rect width="1000" height="640" fill={p.bg}/><rect x="52" y="50" width="5" height="27" rx="2" fill={p.colors[0]}/><text x="73" y="73" fill={p.ink} fontSize="27" fontWeight="700">{short(title || table.headers[ycol], 30)}</text><text x="73" y="105" fill={p.ink} opacity=".7" fontSize="16">{short(subtitle, 60)}</text>
    {type !== 'pie' ? <>
      <text x={left} y={top - 15} fill={p.ink} fontSize="14">{unit || table.headers[ycol]}</text>{scale.values.map(v => <g key={v}><line x1={left} x2={right} y1={y(v)} y2={y(v)} stroke={p.grid} strokeDasharray={v === 0 ? undefined : '4 5'}/><text x={left - 14} y={y(v) + 5} textAnchor="end" fill={p.ink} opacity=".75" fontSize="14">{format(v)}</text></g>)}
      {type === 'bar' ? vals.map((v, i) => { const slot = chartWidth / vals.length, w = Math.min(68, slot * .65), px = left + slot * (i + .5); return <g key={i}><rect x={px - w / 2} y={Math.min(y(v), y(0))} width={w} height={Math.max(1, Math.abs(y(v) - y(0)))} rx="3" fill={p.colors[0]} opacity={i === vals.length - 1 ? '1' : '.8'}><title>{`${labels[i]}：${v}${unit}`}</title></rect>{vals.length <= 15 && <text x={px} y={v >= 0 ? y(v) - 9 : y(v) + 20} textAnchor="middle" fontSize="14" fill={p.ink}>{format(v)}</text>}</g>; }) : <>
        <polyline fill="none" stroke={p.colors[0]} strokeWidth="4" strokeLinejoin="round" points={vals.map((v, i) => `${left + (vals.length === 1 ? chartWidth / 2 : chartWidth * i / (vals.length - 1))},${y(v)}`).join(' ')}/>{vals.map((v, i) => <circle key={i} cx={left + (vals.length === 1 ? chartWidth / 2 : chartWidth * i / (vals.length - 1))} cy={y(v)} r={vals.length > 30 ? 2 : 5} fill={p.colors[0]} stroke={p.bg} strokeWidth="2"><title>{`${labels[i]}：${v}${unit}`}</title></circle>)}</>}
      {labels.map((label, i) => { if (i % Math.max(1, Math.ceil(labels.length / 12)) !== 0 && i !== labels.length - 1) return null; const px = type === 'bar' ? left + chartWidth * (i + .5) / vals.length : left + (vals.length === 1 ? chartWidth / 2 : chartWidth * i / (vals.length - 1)); return <text key={i} x={px} y={bottom + 30} textAnchor="middle" fill={p.ink} fontSize="14">{short(label, labels.length > 10 ? 5 : 9)}</text>; })}<text x={(left + right) / 2} y={bottom + 66} textAnchor="middle" fill={p.ink} fontSize="15" opacity=".8">{table.headers[xcol]}</text>
    </> : <>
      {vals.map((v, i) => { const next = angle + v / sum * Math.PI * 2, mid = (angle + next) / 2, r = 159, cx = 340, cy = 339; const a = [cx + r * Math.cos(angle), cy + r * Math.sin(angle)], b = [cx + r * Math.cos(next), cy + r * Math.sin(next)], d = v === sum ? `M ${cx} ${cy-r} A ${r} ${r} 0 1 1 ${cx} ${cy+r} A ${r} ${r} 0 1 1 ${cx} ${cy-r}` : `M ${cx} ${cy} L ${a.join(' ')} A ${r} ${r} 0 ${next-angle > Math.PI ? 1 : 0} 1 ${b.join(' ')} Z`; angle = next; return <g key={i}><path d={d} fill={p.colors[i % p.colors.length]} stroke={p.bg} strokeWidth="3"><title>{`${labels[i]}：${v}（${(v / sum * 100).toFixed(1)}%）`}</title></path>{v/sum > .065 && <text x={cx + 130 * Math.cos(mid)} y={cy + 130 * Math.sin(mid) + 5} textAnchor="middle" fill={theme === 'poster' ? '#182438' : '#fff'} fontSize="15" fontWeight="700">{(v/sum*100).toFixed(0)}%</text>}</g>; })}
      <circle cx="340" cy="339" r="92" fill={p.bg}/><text x="340" y="334" textAnchor="middle" fontSize="28" fill={p.ink} fontWeight="700">{format(sum)}</text><text x="340" y="364" textAnchor="middle" fontSize="15" fill={p.ink} opacity=".7">合计{unit && ` / ${unit}`}</text>
      {labels.map((l, i) => <g key={i} transform={`translate(580 ${166 + i * 32})`}><rect y="-10" width="12" height="12" rx="3" fill={p.colors[i % p.colors.length]}/><text x="24" y="0" fill={p.ink} fontSize="16">{short(l, 12)}</text><text x="335" y="0" textAnchor="end" fill={p.ink} fontSize="15">{(vals[i]/sum*100).toFixed(1)}%</text></g>)}
    </>}
    <line x1="52" y1="581" x2="948" y2="581" stroke={p.grid}/><text x="53" y="611" fontSize="13" fill={p.ink} opacity=".65">{short(source ? `来源：${source}` : '数据小画室', 85)}</text><text x="948" y="611" textAnchor="end" fontSize="13" fill={p.ink} opacity=".65">{table.rows.length} 条数据</text>
  </svg>;
}
export default function DataStudio() {
  const [raw, setRaw] = useState(sample), [applied, setApplied] = useState(sample), [table, setTable] = useState(() => parseTable(sample)), [error, setError] = useState('');
  const [xcol, setX] = useState(0), [ycol, setY] = useState(1), [type, setType] = useState<ChartType>('bar'), [theme, setTheme] = useState<Theme>('report');
  const [title, setTitle] = useState('上半年收入一览'), [subtitle, setSubtitle] = useState('2026 年 1–6 月 · 示例数据'), [unit, setUnit] = useState('元'), [source, setSource] = useState('');
  const svg = useRef<SVGSVGElement>(null); const vals = useMemo(() => table.rows.map(r => numberValue(r[ycol])!), [table, ycol]);
  useWebTool({ name: 'set_chart_data', description: 'Replace the visible chart table with tab-separated or CSV text. First row must contain column headers. Data stays in the page.', inputSchema: { type: 'object', properties: { text: { type: 'string' } }, required: ['text'], additionalProperties: false }, execute: input => { const value = input as { text?: unknown }; if (!value || typeof value.text !== 'string') throw Error('text must be a string'); const next = parseTable(value.text); setRaw(value.text); setApplied(value.text); setTable(next); setX(0); setY(next.numericColumns[0]); setError(''); return { rows: next.rows.length, headers: next.headers }; } });
  const pieError = type === 'pie' && (vals.some(v => v < 0) || vals.reduce((a, b) => a + b, 0) <= 0 || vals.length > 12) ? '占比图需要非负数且合计大于零，最多 12 个分类；可切换为柱状图。' : '';
  const apply = () => { try { const next = parseTable(raw); setTable(next); setApplied(raw); setError(''); if (xcol >= next.headers.length) setX(0); const y = next.numericColumns.includes(ycol) ? ycol : next.numericColumns[0]; setY(y); if (applied === sample && raw !== sample) { if (title === '上半年收入一览') setTitle(`${next.headers[y]}概览`); if (subtitle === '2026 年 1–6 月 · 示例数据') setSubtitle(''); if (unit === '元') setUnit(''); } toast.success('数据已更新'); } catch (e) { setError((e as Error).message); } };
  const exportImage = async (kind: 'svg' | 'png') => { if (!svg.current || pieError) return; const str = new XMLSerializer().serializeToString(svg.current); if (kind === 'svg') { download(`${title || '图表'}.svg`, str, 'image/svg+xml'); return; } const url = URL.createObjectURL(new Blob([str], { type: 'image/svg+xml' })); try { const img = new Image(); await new Promise<void>((resolve, reject) => { img.onload = () => resolve(); img.onerror = reject; img.src = url; }); const c = document.createElement('canvas'); c.width = 2000; c.height = 1280; const ctx = c.getContext('2d')!; ctx.drawImage(img, 0, 0, 2000, 1280); const blob = await new Promise<Blob | null>(r => c.toBlob(r, 'image/png')); if (!blob) throw Error('导出失败'); download(`${title || '图表'}.png`, blob); toast.success('图片已导出'); } catch { toast.error('图片导出失败，可以先导出 SVG。'); } finally { URL.revokeObjectURL(url); } };
  return <section className="tool-page"><div className="page-heading"><div><p className="eyebrow">01 / DATA STUDIO</p><h1>数据小画室</h1><p className="page-description">一份表格，一张讲清楚事情的图。</p></div><div className="heading-actions"><Button variant="outline" disabled={!!pieError} onClick={() => void exportImage('svg')}><FileText size={16}/> SVG</Button><Button disabled={!!pieError} onClick={() => void exportImage('png')}><Download size={16}/> 导出图片</Button></div></div>
    <div className="data-layout"><aside className="control-panel"><div className="panel-heading"><Table2 size={17}/><h2>你的数据</h2><span className="sample-badge">{applied === sample ? '示例' : '自定义'}</span></div><p className="muted help">从 Excel 复制表格粘贴到这里。首行为表头，支持制表符或 CSV。</p><textarea id="data-input" aria-label="表格数据" className="data-input" value={raw} onChange={e => setRaw(e.target.value)} spellCheck={false}/>{error && <p role="alert" className="field-error">{error}</p>}<div className="input-actions"><Button onClick={apply}>生成图表</Button><Button variant="ghost" size="icon" aria-label="填入示例数据" onClick={() => { setRaw(sample); setError(''); }}><RotateCcw size={16}/></Button></div>{raw !== applied && <p className="muted help">有未应用的修改，点击“生成图表”更新。</p>}
      <div className="control-divider"/><label className="field">横轴 / 分类<Pick value={String(xcol)} onChange={v => setX(Number(v))} options={table.headers.map((h, i) => ({ value: String(i), label: h }))} label="分类列"/></label><label className="field">数值<Pick value={String(ycol)} onChange={v => setY(Number(v))} options={table.numericColumns.map(i => ({ value: String(i), label: table.headers[i] }))} label="数值列"/></label>
      <label className="field">图表标题<input aria-label="图表标题" value={title} maxLength={100} onChange={e => setTitle(e.target.value)}/></label><label className="field">副标题<input value={subtitle} maxLength={180} onChange={e => setSubtitle(e.target.value)}/></label><label className="field">单位<input value={unit} maxLength={30} onChange={e => setUnit(e.target.value)} placeholder="例如：元、%、人"/></label><label className="field">来源<input value={source} maxLength={160} onChange={e => setSource(e.target.value)} placeholder="可选，写明数据出处"/></label>
    </aside><div className="data-main"><div className="chart-toolbar"><Tabs value={type} onValueChange={v => setType(v as ChartType)}><TabsList className="tool-tabs"><TabsTrigger value="bar"><BarChart3 size={16}/>柱状图</TabsTrigger><TabsTrigger value="line"><LineChart size={16}/>折线图</TabsTrigger><TabsTrigger value="pie"><PieChart size={16}/>占比图</TabsTrigger></TabsList></Tabs><div className="palette-picker"><Palette size={16}/><Pick value={theme} onChange={v => setTheme(v as Theme)} label="图表风格" options={Object.entries(palettes).map(([value, p]) => ({ value, label: p.name }))}/></div></div>
      <div className="chart-stage">{pieError ? <div className="empty-state" role="alert"><PieChart size={40}/><p>{pieError}</p></div> : <Chart table={table} xcol={xcol} ycol={ycol} type={type} theme={theme} title={title} subtitle={subtitle} unit={unit} source={source} svgRef={svg}/>}</div>
      <div className="chart-meta"><span>预览与导出使用同一张图</span><span>PNG · 2000 × 1280 / SVG · 可缩放</span></div><div className="data-summary"><div><span>数据条数</span><strong>{vals.length}</strong></div><div><span>{table.headers[ycol]}合计</span><strong>{format(vals.reduce((a, b) => a + b, 0))}<small>{unit}</small></strong></div><div><span>平均值</span><strong>{format(vals.reduce((a, b) => a + b, 0) / vals.length)}<small>{unit}</small></strong></div></div>
      <details className="table-preview"><summary>查看数据表 · {table.rows.length} 行</summary><div className="table-scroll"><Table><TableHeader><TableRow>{table.headers.map(h => <TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{table.rows.map((r, i) => <TableRow key={i}>{r.map((v, j) => <TableCell key={j}>{v}</TableCell>)}</TableRow>)}</TableBody></Table></div></details>
    </div></div></section>;
}

