'use client';
import { useEffect, useRef, useState } from 'react';
import { Plus, Hand, MousePointer2, Link2, Focus, Minus, FileText, Download, Upload, Trash2, Network, Copy, X } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { BoardData, NodeData, boardSchema, nodeTypes, typeLabels, makeId, sampleBoard, outline } from '@/lib/studio-model';
import { Confirm, Doc, Pick, StorageNotice, download } from './shared';
import { useWebTool } from './web-tools';
type View = { x: number; y: number; zoom: number };
const W = 242, H = 184;
export default function IdeaBoard({ doc }: { doc: Doc<BoardData> }) {
  const { data: board, update } = doc;
  const [selected, setSelected] = useState<string | null>(null), [mode, setMode] = useState('select'), [view, setView] = useState<View>({ x: 40, y: 40, zoom: .82 });
  const [showOutline, setShowOutline] = useState(false), [confirm, setConfirm] = useState<'sample' | 'delete' | 'import' | null>(null), [incoming, setIncoming] = useState<BoardData | null>(null);
  const boardRef = useRef<HTMLDivElement>(null), input = useRef<HTMLInputElement>(null), viewRef = useRef(view), pointer = useRef<{ id: number; startX: number; startY: number; view: View; node?: NodeData } | null>(null);
  viewRef.current = view;
  const node = board.nodes.find(n => n.id === selected);
  useWebTool({ name: 'add_idea_cards', description: 'Add a batch of typed cards to the current idea board and queue the same browser-local save used by the visible editor.', inputSchema: { type: 'object', properties: { cards: { type: 'array', minItems: 1, maxItems: 30, items: { type: 'object', properties: { title: { type: 'string' }, body: { type: 'string' }, type: { type: 'string', enum: [...nodeTypes] } }, required: ['title', 'body', 'type'], additionalProperties: false } } }, required: ['cards'], additionalProperties: false }, execute: input => { if (!doc.ready || doc.status === 'conflict') throw Error('Board is unavailable or has a save conflict'); const v = input as { cards?: unknown }; if (!v || !Array.isArray(v.cards) || !v.cards.length || v.cards.length > 30) throw Error('Provide 1–30 cards'); const nodes = v.cards.map((c, i) => ({ ...c, id: makeId(), x: 80 + (i % 3) * 285, y: 80 + Math.floor(i / 3) * 225 })); const result = boardSchema.safeParse({ ...board, nodes: [...board.nodes, ...nodes] }); if (!result.success) throw Error(result.error.issues[0].message); update(result.data); return { created: nodes.map(n => n.id), save: 'queued' }; } });
  const backup = () => download('观点板备份.json', JSON.stringify({ version: 1, kind: 'board', data: board }, null, 2));
  function fit(data = board) { const r = boardRef.current?.getBoundingClientRect(); if (!r || r.width < 1 || !data.nodes.length) { setView({ x: 40, y: 40, zoom: .82 }); return; } const x0 = Math.min(...data.nodes.map(n => n.x)), y0 = Math.min(...data.nodes.map(n => n.y)), x1 = Math.max(...data.nodes.map(n => n.x + W)), y1 = Math.max(...data.nodes.map(n => n.y + H)); const z = Math.max(.15, Math.min(1.1, (r.width - 80) / (x1 - x0), (r.height - 80) / (y1 - y0))); setView({ x: (r.width - (x1 - x0) * z) / 2 - x0 * z, y: (r.height - (y1 - y0) * z) / 2 - y0 * z, zoom: z }); }
  const initialFit = useRef(false);
  useEffect(() => { if (doc.ready && !initialFit.current) { initialFit.current = true; requestAnimationFrame(() => fit()); } }, [doc.ready]);
  useEffect(() => { const el = boardRef.current; if (!el) return; const wheel = (e: WheelEvent) => { e.preventDefault(); const v = viewRef.current; if (e.ctrlKey || e.metaKey) { const r = el.getBoundingClientRect(), z = Math.max(.15, Math.min(2, v.zoom * Math.exp(-e.deltaY * .008))), px = e.clientX - r.left, py = e.clientY - r.top; setView({ x: px - (px - v.x) * z / v.zoom, y: py - (py - v.y) * z / v.zoom, zoom: z }); } else setView({ ...v, x: v.x - e.deltaX, y: v.y - e.deltaY }); }; el.addEventListener('wheel', wheel, { passive: false }); return () => el.removeEventListener('wheel', wheel); }, []);
  const zoom = (factor: number) => { const r = boardRef.current?.getBoundingClientRect(); if (!r) return; const v = viewRef.current, z = Math.max(.15, Math.min(2, v.zoom * factor)); setView({ x: r.width / 2 - (r.width / 2 - v.x) * z / v.zoom, y: r.height / 2 - (r.height / 2 - v.y) * z / v.zoom, zoom: z }); };
  function add(type: NodeData['type']) { if (board.nodes.length >= 150) { toast.error('每张观点板最多 150 张卡片。'); return; } const r = boardRef.current?.getBoundingClientRect(), v = viewRef.current; const id = makeId(); update(b => ({ ...b, nodes: [...b.nodes, { id, type, title: `新的${typeLabels[type]}`, body: '', x: Math.max(-5000, Math.min(5000, ((r?.width || 700) / 2 - v.x) / v.zoom - W / 2 + Math.random() * 25)), y: Math.max(-5000, Math.min(5000, ((r?.height || 600) / 2 - v.y) / v.zoom - H / 2 + Math.random() * 25)) }] })); setSelected(id); setMode('select'); }
  const edit = (change: Partial<NodeData>) => { if (selected) update(b => ({ ...b, nodes: b.nodes.map(n => n.id === selected ? { ...n, ...change } : n) })); };
  function remove() { update(b => ({ ...b, nodes: b.nodes.filter(n => n.id !== selected), edges: b.edges.filter(e => e.from !== selected && e.to !== selected) })); setSelected(null); setConfirm(null); }
  function start(e: React.PointerEvent, n?: NodeData) {
    if (!doc.ready || pointer.current || (e.button !== 0 && e.button !== 2)) return;
    e.preventDefault(); e.stopPropagation();
    if (mode === 'connect' && n && e.button === 0) { if (!selected) { setSelected(n.id); toast('再点另一张卡片，建立连接。'); } else if (selected !== n.id) { if (board.edges.some(l => l.from === selected && l.to === n.id)) toast('这两张卡片已经连接。'); else if (board.edges.length >= 500) toast.error('连线数量已达上限。'); else { update(b => ({ ...b, edges: [...b.edges, { id: makeId(), from: selected, to: n.id }] })); toast.success('连接已建立'); } setMode('select'); } return; }
    if (n && mode !== 'pan' && e.button === 0) setSelected(n.id); else if (!n && mode === 'select') setSelected(null);
    pointer.current = { id: e.pointerId, startX: e.clientX, startY: e.clientY, view: viewRef.current, node: n && mode !== 'pan' && e.button === 0 ? { ...n } : undefined };
    boardRef.current?.setPointerCapture(e.pointerId);
  }
  function move(e: React.PointerEvent) { const p = pointer.current; if (!p || p.id !== e.pointerId) return; const dx = e.clientX - p.startX, dy = e.clientY - p.startY; if (p.node) update(b => ({ ...b, nodes: b.nodes.map(n => n.id === p.node!.id ? { ...n, x: Math.max(-5000, Math.min(5000, p.node!.x + dx / p.view.zoom)), y: Math.max(-5000, Math.min(5000, p.node!.y + dy / p.view.zoom)) } : n) })); else setView({ ...p.view, x: p.view.x + dx, y: p.view.y + dy }); }
  const end = (e: React.PointerEvent) => { if (pointer.current?.id === e.pointerId) pointer.current = null; };
  const importFile = async (file?: File) => { if (!file) return; try { if (file.size > 2000000) throw Error('文件过大'); const v = JSON.parse(await file.text()); const result = boardSchema.safeParse(v.kind === 'board' ? v.data : v); if (!result.success) throw Error('不是有效的观点板备份'); setIncoming(result.data); setConfirm('import'); } catch (e) { toast.error((e as Error).message); } if (input.current) input.current.value = ''; };
  const text = outline(board);
  return <section className="tool-page board-page"><div className="page-heading"><div><p className="eyebrow">02 / IDEA BOARD</p><h1>观点整理板</h1><p className="page-description">让论点、证据和反例，在同一张桌面上相遇。</p></div><div className="heading-actions"><Button variant="outline" disabled={!doc.ready} onClick={() => { if (board.nodes.length) setConfirm('sample'); else { const s = sampleBoard(); update(s); fit(s); } }}>试试示例</Button><Button disabled={!doc.ready} onClick={() => setShowOutline(true)}><FileText size={16}/> 整理成提纲</Button></div></div>
    <StorageNotice doc={doc} exportBackup={backup}/><fieldset disabled={!doc.ready} className="tool-fieldset"><div className="board-toolbar"><div className="board-add">{nodeTypes.map(t => <Button key={t} className={`node-add ${t}`} variant="outline" onClick={() => add(t)}><Plus size={15}/>{typeLabels[t]}</Button>)}</div><Tabs value={mode} onValueChange={setMode}><TabsList className="tool-tabs"><TabsTrigger value="select" aria-label="选择与拖动卡片"><MousePointer2 size={16}/>选择</TabsTrigger><TabsTrigger value="pan"><Hand size={16}/>平移</TabsTrigger><TabsTrigger value="connect"><Link2 size={16}/>连接</TabsTrigger></TabsList></Tabs><div className="board-files"><Button variant="ghost" size="icon" aria-label="导出观点板备份" onClick={backup}><Download size={17}/></Button><Button variant="ghost" size="icon" aria-label="导入观点板备份" onClick={() => input.current?.click()}><Upload size={17}/></Button><input ref={input} type="file" accept=".json,application/json" hidden onChange={e => void importFile(e.target.files?.[0])}/></div></div>
      <div className="board-layout"><div ref={boardRef} className={`board-canvas mode-${mode}`} data-testid="board-canvas" onPointerDown={e => start(e)} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onLostPointerCapture={end} onContextMenu={e => e.preventDefault()} style={{ backgroundPosition: `${view.x}px ${view.y}px`, backgroundSize: `${24 * view.zoom}px ${24 * view.zoom}px` }}>
        <div className="board-transform" style={{ transform: `translate(${view.x}px,${view.y}px) scale(${view.zoom})` }}>
          <svg className="board-links" width="1" height="1" aria-hidden="true"><defs><marker id="board-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#73829b"/></marker></defs>{board.edges.map(e => { const a = board.nodes.find(n => n.id === e.from), b = board.nodes.find(n => n.id === e.to); if (!a || !b) return null; const down = b.y > a.y, ax = a.x + W / 2, ay = a.y + (down ? H : 0), bx = b.x + W / 2, by = b.y + (down ? 0 : H), gap = Math.max(70, Math.abs(by - ay) * .5); return <path key={e.id} d={`M${ax} ${ay} C${ax} ${ay + (down ? gap : -gap)} ${bx} ${by + (down ? -gap : gap)} ${bx} ${by}`} fill="none" stroke="#73829b" strokeWidth="2" markerEnd="url(#board-arrow)"/>; })}</svg>
          {board.nodes.map(n => <div key={n.id} role="button" tabIndex={0} aria-label={`${typeLabels[n.type]}：${n.title}`} aria-pressed={n.id === selected} className={`idea-card ${n.type} ${n.id === selected ? 'selected' : ''}`} data-node-id={n.id} style={{ left: n.x, top: n.y, width: W, height: H }} onPointerDown={e => start(e, n)} onKeyDown={e => { if (e.key === 'Enter') { setSelected(n.id); return; } const delta: Record<string, [number, number]> = { ArrowLeft: [-10, 0], ArrowRight: [10, 0], ArrowUp: [0, -10], ArrowDown: [0, 10] }; if (delta[e.key]) { e.preventDefault(); const [dx, dy] = delta[e.key]; update(b => ({ ...b, nodes: b.nodes.map(x => x.id === n.id ? { ...x, x: Math.max(-5000, Math.min(5000, x.x + dx)), y: Math.max(-5000, Math.min(5000, x.y + dy)) } : x) })); } }}><span className={`node-type ${n.type}`}>{typeLabels[n.type]}</span><span className="card-grip">⠿</span><h3>{n.title || '未命名卡片'}</h3><p>{n.body || '选中卡片，在右侧写下你的想法。'}</p></div>)}
        </div>{!board.nodes.length && <div className="board-empty"><Network size={42}/><h2>从一个想法开始</h2><p>添加论点卡片，或打开示例看看。</p><Button onClick={() => add('claim')}><Plus size={16}/> 第一个论点</Button></div>}
        <div className="board-hint">{mode === 'connect' ? selected ? '点击另一张卡片，连接到当前卡片' : '先选起点卡片，再选终点卡片' : '拖动卡片 · 拖动空白平移 · Ctrl + 滚轮缩放'}</div><div className="board-zoom" onPointerDown={e => e.stopPropagation()}><Button variant="ghost" size="icon" aria-label="缩小观点板" onClick={() => zoom(1/1.2)}><Minus size={17}/></Button><span>{Math.round(view.zoom*100)}%</span><Button variant="ghost" size="icon" aria-label="放大观点板" onClick={() => zoom(1.2)}><Plus size={17}/></Button><Button variant="ghost" size="icon" aria-label="全景居中" onClick={() => fit()}><Focus size={17}/></Button></div>
      </div><aside className="board-inspector"><div className="panel-heading"><h2>{node ? '编辑卡片' : '画板信息'}</h2>{node && <Button variant="ghost" size="icon" aria-label="取消选中" onClick={() => setSelected(null)}><X size={16}/></Button>}</div>{node ? <><label className="field">类型<Pick value={node.type} onChange={v => edit({ type: v as NodeData['type'] })} label="卡片类型" options={nodeTypes.map(t => ({ value: t, label: typeLabels[t] }))}/></label><label className="field">标题<input aria-label="卡片标题" value={node.title} maxLength={160} onChange={e => edit({ title: e.target.value })}/></label><label className="field">内容与来源<textarea aria-label="卡片内容" value={node.body} maxLength={6000} onChange={e => edit({ body: e.target.value })} rows={8} placeholder="写下证据、例子，或资料出处…"/></label><div className="connections"><h3>相关连线</h3>{board.edges.filter(e => e.from === node.id || e.to === node.id).map(e => <div key={e.id}><span>{e.from === node.id ? '连接到' : '来自'}：{board.nodes.find(n => n.id === (e.from === node.id ? e.to : e.from))?.title}</span><Button variant="ghost" size="icon" aria-label="删除连线" onClick={() => update(b => ({ ...b, edges: b.edges.filter(l => l.id !== e.id) }))}><X size={14}/></Button></div>)}{!board.edges.some(e => e.from === node.id || e.to === node.id) && <p className="muted help">还没有连线。选择“连接”，再点另一张卡片。</p>}</div><Button variant="outline" className="danger" onClick={() => setConfirm('delete')}><Trash2 size={16}/> 删除卡片</Button></> : <><label className="field">主题<input aria-label="观点板主题" value={board.title} maxLength={160} onChange={e => update(b => ({ ...b, title: e.target.value }))}/></label><div className="board-count"><strong>{board.nodes.length}<span>卡片</span></strong><strong>{board.edges.length}<span>连线</span></strong></div><div className="inspector-guide"><h3>把想法搭起来</h3><p><span className="type-dot claim"/>论点：你想表达的判断</p><p><span className="type-dot evidence"/>证据：数据、材料与来源</p><p><span className="type-dot counter"/>反例：不同意见与限制</p><p><span className="type-dot note"/>笔记：补充与下一步</p><p className="muted">连线方向从主论点指向支撑材料，提纲按这个顺序展开。选中卡片后可用方向键移动。</p></div></>}</aside></div></fieldset>
    <Dialog open={showOutline} onOpenChange={setShowOutline}><DialogContent className="outline-dialog"><DialogHeader><DialogTitle>你的观点提纲</DialogTitle><DialogDescription>按照连线层级整理。未连接的卡片也会保留。</DialogDescription></DialogHeader><textarea aria-label="生成的提纲" value={text} readOnly rows={16}/><div className="heading-actions"><Button variant="outline" onClick={async () => { try { await navigator.clipboard.writeText(text); toast.success('提纲已复制'); } catch { toast.error('无法复制，请选中文字或导出文件。'); } }}><Copy size={16}/> 复制</Button><Button onClick={() => download(`${board.title || '观点提纲'}.md`, text, 'text/markdown;charset=utf-8')}><Download size={16}/> 导出提纲</Button></div></DialogContent></Dialog>
    <Confirm open={!!confirm} onClose={() => setConfirm(null)} title={confirm === 'delete' ? '删除这张卡片？' : confirm === 'import' ? '导入备份并替换画板？' : '用示例替换当前画板？'} description={confirm === 'delete' ? '这张卡片与相关连线将被删除。' : '当前画板会被替换。需要保留时，请先导出备份。'} onConfirm={() => { if (confirm === 'delete') remove(); else { const next = confirm === 'import' ? incoming! : sampleBoard(); update(next); setSelected(null); setConfirm(null); fit(next); } }}/>
  </section>;
}
