'use client';
import { useState } from 'react';
import { toast } from 'sonner';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { Button } from '@/components/ui/button';
export function Pick({ value, onChange, options, label }: { value: string; onChange: (v: string) => void; options: { value: string; label: string }[]; label: string }) { return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="pick"><SelectValue/></SelectTrigger><SelectContent>{options.map(o => <SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>; }
export function download(name: string, data: Blob | string, type = 'application/json') { const url = URL.createObjectURL(data instanceof Blob ? data : new Blob([data], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 3000); }
export function Confirm({ open, onClose, onConfirm, title, description }: { open: boolean; onClose: () => void; onConfirm: () => void; title: string; description: string }) { return <AlertDialog open={open} onOpenChange={v => { if (!v) onClose(); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={onConfirm}>确认</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>; }
export type Doc<T> = { data: T; update: (value: T | ((old: T) => T)) => void; status: 'loading' | 'saving' | 'saved' | 'error' | 'conflict'; ready: boolean; retry: () => void; reload: () => Promise<void> };
export { useLocalDocument as useDocument } from './local-storage';
export function StorageNotice<T>({ doc, exportBackup }: { doc: Doc<T>; exportBackup: () => void }) { const [confirm, setConfirm] = useState(false); if (doc.status !== 'error' && doc.status !== 'conflict') return null; return <><div className="storage-notice" role="alert"><span>{doc.status === 'conflict' ? '记录已在另一页面更新。本页修改尚未保存。' : doc.ready ? '保存失败。本页内容还在，请重试或导出备份。' : '读取失败，暂不能编辑。'}</span>{doc.status !== 'conflict' && <Button variant="outline" onClick={doc.retry}>重试</Button>}{doc.ready && <Button variant="outline" onClick={exportBackup}>导出本页备份</Button>}{doc.status === 'conflict' && <Button variant="outline" onClick={() => setConfirm(true)}>读取最新版本</Button>}</div><Confirm open={confirm} onClose={() => setConfirm(false)} title="读取最新版本？" description="本页尚未保存的修改会被替换。请先导出本页备份。" onConfirm={() => { setConfirm(false); void doc.reload(); }}/></>; }

