'use client';
import { useEffect, useRef, useState } from 'react';
import { Play, Square, Plus, Clock3, Download, Upload, CalendarDays, Pencil, Trash2, Target, ChevronLeft, ChevronRight } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { categories, categoryColors, Category, TimeData, TimeEntry, timeSchema, dayEntries, dayBounds, localDate, minutes, duration, overlaps, makeId } from '@/lib/studio-model';
import { Confirm, Doc, Pick, StorageNotice, download } from './shared';
import { useWebTool } from './web-tools';
const prettyMinutes = (v: number) => v >= 60 ? `${Math.floor(v/60)} 小时 ${Math.floor(v%60)} 分` : `${Math.floor(v)} 分钟`;
function localInput(ms: number) { const d = new Date(ms); return `${localDate(d)}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`; }
const timeLabel = (ms: number) => new Date(ms).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit', hour12: false });
type Form = { id: string; title: string; category: Category; start: string; end: string };
export default function TimeLedger({ doc }: { doc: Doc<TimeData> }) {
  const { data, update } = doc; const [now, setNow] = useState(0), [day, setDay] = useState(''), [title, setTitle] = useState(''), [category, setCategory] = useState<Category>('学习');
  const [form, setForm] = useState<Form | null>(null), [formError, setFormError] = useState(''), [removeId, setRemoveId] = useState<string | null>(null), [incoming, setIncoming] = useState<TimeData | null>(null);
  const input = useRef<HTMLInputElement>(null); const [goalInput, setGoalInput] = useState(String(data.goal));
  useWebTool({ name: 'create_time_entries', description: 'Create completed time entries from epoch milliseconds and queue browser-local saving. Rejects overlaps, future entries and invalid durations.', inputSchema: { type: 'object', properties: { entries: { type: 'array', minItems: 1, maxItems: 30, items: { type: 'object', properties: { title: { type: 'string' }, category: { type: 'string', enum: [...categories] }, start: { type: 'number' }, end: { type: 'number' } }, required: ['title', 'category', 'start', 'end'], additionalProperties: false } } }, required: ['entries'], additionalProperties: false }, execute: input => { if (!doc.ready || doc.status === 'conflict') throw Error('Ledger is unavailable or has a save conflict'); const v = input as { entries?: unknown }; if (!v || !Array.isArray(v.entries) || !v.entries.length || v.entries.length > 30) throw Error('Provide 1–30 entries'); const entries = v.entries.map(e => ({ ...e, id: makeId() })); const result = timeSchema.safeParse({ ...data, entries: [...data.entries, ...entries] }); if (!result.success) throw Error(result.error.issues[0].message); for (const e of entries) { if (e.end > Date.now() || overlaps(result.data.entries, e.start, e.end, e.id) || (data.active && e.end > data.active.start)) throw Error('Entries overlap or are in the future'); } update(result.data); return { created: entries.map(e => e.id), save: 'queued' }; } });
  useEffect(() => { setNow(Date.now()); setDay(localDate()); const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => setGoalInput(String(data.goal)), [data.goal]);
  const today = now ? localDate(new Date(now)) : ''; const effectiveDay = day || today;
  const all = data.active && now > data.active.start ? [...data.entries, { ...data.active, end: now }] : data.entries;
  const shown = effectiveDay ? dayEntries(all, effectiveDay).sort((a,b) => a.start-b.start) : [];
  const total = minutes(shown), focus = minutes(shown.filter(e => e.category === '学习' || e.category === '工作'));
  const totals = categories.map(c => ({ category: c, minutes: minutes(shown.filter(e => e.category === c)) }));
  const [startDay, endDay] = effectiveDay ? dayBounds(effectiveDay) : [0, 1];
  const backup = () => download('时间账本备份.json', JSON.stringify({ version: 1, kind: 'time', data }, null, 2));
  const startTimer = () => { if (!title.trim()) { toast.error('先给这段时间取个名字。'); return; } const start = Date.now(); if (data.entries.some(e => e.end > start)) { toast.error('已有未来时间记录，请先检查记录。'); return; } update(t => ({ ...t, active: { id: makeId(), title: title.trim(), category, start } })); setNow(start); toast.success('开始计时，切换工具也会继续。'); };
  const stopTimer = () => { const active = data.active; if (!active) return; const end = Date.now(); if (end <= active.start) { toast.error('请至少计时一秒。'); return; } if (overlaps(data.entries, active.start, end)) { toast.error('计时与已有记录重叠，请先检查记录。'); return; } const chunks: TimeEntry[] = []; for (let start = active.start; start < end;) { const stop = Math.min(end, start + 7 * 86400000); chunks.push({ ...active, id: chunks.length ? makeId() : active.id, start, end: stop }); start = stop; } if (data.entries.length + chunks.length > 5000) { toast.error('记录已达上限，请先导出备份并整理旧记录。'); return; } update(t => ({ ...t, active: null, entries: [...t.entries, ...chunks] })); setTitle(''); toast.success('这段时间已记入账本'); };
  const openForm = (entry?: TimeEntry) => { setFormError(''); setForm(entry ? { id: entry.id, title: entry.title, category: entry.category, start: localInput(entry.start), end: localInput(entry.end) } : { id: '', title: '', category: '学习', start: `${effectiveDay}T09:00`, end: `${effectiveDay}T10:00` }); };
  function saveForm(e: React.FormEvent) { e.preventDefault(); if (!form) return; const start = +new Date(form.start), end = +new Date(form.end), now = Date.now(); const next: TimeEntry = { id: form.id || makeId(), title: form.title.trim(), category: form.category, start, end }; if (!next.title) { setFormError('请输入事项名称。'); return; } if (!Number.isFinite(start) || !Number.isFinite(end) || end <= start || end-start > 7*86400000) { setFormError('结束时间须晚于开始时间，单条记录不超过七天。'); return; } if (end > now) { setFormError('时间账本记录已发生的时间，结束时间不能晚于现在。'); return; } if (overlaps(data.entries, start, end, form.id) || (data.active && end > data.active.start)) { setFormError('这段时间与已有记录或正在进行的计时重叠，请调整起止时间。'); return; } if (!form.id && data.entries.length >= 5000) { setFormError('最多保存 5000 条记录，请先备份并整理旧记录。'); return; } update(t => ({ ...t, entries: form.id ? t.entries.map(x => x.id === form.id ? next : x) : [...t.entries, next] })); setForm(null); toast.success('记录已更新'); }
  const moveDay = (delta: number) => { const d = new Date(`${effectiveDay}T12:00:00`); d.setDate(d.getDate()+delta); const next = localDate(d); if (next <= today) setDay(next); };
  const exportCSV = () => { const escape = (s: string) => `"${(/^[=+@-]/.test(s) ? "'" : '') + s.replace(/"/g, '""')}"`; const lines = ['事项,分类,开始时间,结束时间,分钟数', ...data.entries.slice().sort((a,b) => a.start-b.start).map(e => [escape(e.title), escape(e.category), escape(localInput(e.start)), escape(localInput(e.end)), ((e.end-e.start)/60000).toFixed(2)].join(','))]; download('时间账本.csv', '\uFEFF'+lines.join('\r\n'), 'text/csv;charset=utf-8'); };
  const importFile = async (file?: File) => { if (!file) return; try { if (file.size > 2000000) throw Error('文件过大'); const v = JSON.parse(await file.text()); const parsed = timeSchema.safeParse(v.kind === 'time' ? v.data : v); if (!parsed.success) throw Error('不是有效的时间账本备份'); const entries = parsed.data.entries.slice().sort((a,b) => a.start-b.start); if (entries.some((e,i) => i>0 && e.start < entries[i-1].end) || entries.some(e => e.end > Date.now())) throw Error('备份中存在重叠或未来的记录'); setIncoming({ ...parsed.data, active: null }); } catch (e) { toast.error((e as Error).message); } if (input.current) input.current.value = ''; };
  const week = Array.from({ length: 7 }, (_, i) => { const d = new Date(`${effectiveDay || '2000-01-01'}T12:00:00`); d.setDate(d.getDate()-6+i); const date = localDate(d); return { day: date, label: `${d.getMonth()+1}/${d.getDate()}`, value: minutes(dayEntries(all, date)) }; }); const weekMax = Math.max(60, ...week.map(d => d.value));
  return <section className="tool-page time-page"><div className="page-heading"><div><p className="eyebrow">03 / TIME LEDGER</p><h1>时间账本</h1><p className="page-description">记下时间的去向，给每一天留一点依据。</p></div><div className="heading-actions"><Button variant="outline" disabled={!doc.ready} onClick={exportCSV}><Download size={16}/> 导出 CSV</Button><Button disabled={!doc.ready} onClick={() => openForm()}><Plus size={16}/> 补记时间</Button></div></div>
    <StorageNotice doc={doc} exportBackup={backup}/><fieldset disabled={!doc.ready} className="tool-fieldset"><div className="time-layout"><div className="time-main"><div className={`timer-panel ${data.active ? 'running' : ''}`}><div className="timer-heading"><span><Clock3 size={17}/> {data.active ? '正在进行' : '现在，开始一件事'}</span><span className="timer-tag">{data.active ? data.active.category : '一次专心做一件事'}</span></div><div className="timer-digits" aria-label="计时时长">{duration(data.active && now ? now-data.active.start : 0)}</div>{data.active ? <div className="active-task"><strong>{data.active.title}</strong><p>开始于 {new Date(data.active.start).toLocaleString('zh-CN')} · 关闭页面后继续计时</p><Button className="timer-stop" onClick={stopTimer}><Square size={15}/> 结束并记录</Button></div> : <div className="timer-form"><label className="sr-only" htmlFor="timer-title">计时事项</label><input id="timer-title" aria-label="计时事项" value={title} maxLength={160} onChange={e => setTitle(e.target.value)} placeholder="例如：复习公司金融" onKeyDown={e => { if (e.key === 'Enter') startTimer(); }}/><Pick value={category} onChange={v => setCategory(v as Category)} label="计时分类" options={categories.map(c => ({ value: c, label: c }))}/><Button onClick={startTimer}><Play size={16}/> 开始计时</Button></div>}</div>
      <div className="daily-panel"><div className="section-heading"><h2>一天的时间去向</h2><div className="date-nav"><Button variant="ghost" size="icon" aria-label="前一天" onClick={() => moveDay(-1)}><ChevronLeft size={16}/></Button><label className="date-label"><CalendarDays size={15}/><input aria-label="查看日期" type="date" value={effectiveDay} max={today} onChange={e => { if (e.target.value) setDay(e.target.value); }}/></label><Button variant="ghost" size="icon" disabled={effectiveDay >= today} aria-label="后一天" onClick={() => moveDay(1)}><ChevronRight size={16}/></Button>{effectiveDay !== today && <Button variant="ghost" onClick={() => setDay(today)}>今天</Button>}</div></div><div className="timeline"><div className="timeline-track">{shown.map(e => <span key={e.id} title={`${e.title} · ${timeLabel(e.start)}–${timeLabel(e.end)}`} style={{ left: `${(e.start-startDay)/(endDay-startDay)*100}%`, width: `${(e.end-e.start)/(endDay-startDay)*100}%`, background: categoryColors[e.category] }} />)}</div><div className="timeline-labels">{['00:00','06:00','12:00','18:00','24:00'].map(t => <span key={t}>{t}</span>)}</div></div><div className="time-legend">{categories.map(c => <span key={c}><i style={{ background: categoryColors[c] }}/>{c}</span>)}<span><i className="untracked"/>未记录</span></div>
        <div className="entry-list">{shown.length ? shown.map(e => { const active = e.id === data.active?.id; const original = data.entries.find(x => x.id === e.id); return <div className="time-entry" key={e.id}><span className="entry-dot" style={{ background: categoryColors[e.category] }}/><div className="entry-title"><strong>{e.title}{active && <small>进行中</small>}</strong><span>{e.category} · {timeLabel(e.start)}–{e.end === endDay ? '24:00' : timeLabel(e.end)}{original && (original.start !== e.start || original.end !== e.end) ? ' · 跨天记录' : ''}</span></div><span className="entry-duration">{prettyMinutes((e.end-e.start)/60000)}</span>{!active && original && <div className="entry-actions"><Button variant="ghost" size="icon" aria-label={`编辑 ${e.title}`} onClick={() => openForm(original)}><Pencil size={15}/></Button><Button variant="ghost" size="icon" aria-label={`删除 ${e.title}`} onClick={() => setRemoveId(e.id)}><Trash2 size={15}/></Button></div>}</div>; }) : <div className="empty-state"><Clock3 size={34}/><h3>这一天还没有记录</h3><p>开始一次计时，或补记已经做过的事。</p></div>}</div>
      </div></div><aside className="time-side"><div className="day-summary"><span className="eyebrow">{effectiveDay === today ? 'TODAY' : effectiveDay}</span><h2>已记录</h2><strong className="time-total">{(total/60).toFixed(1)}<small>小时</small></strong><p>未记录 {prettyMinutes(Math.max(0, (endDay-startDay)/60000-total))}</p><div className="distribution-bar">{total ? totals.filter(t => t.minutes>0).map(t => <span key={t.category} style={{ width: `${t.minutes/total*100}%`, background: categoryColors[t.category] }}/>) : <span style={{ width: '100%', background: '#e8edf3' }}/>}</div><div className="category-totals">{totals.map(t => <div key={t.category}><span><i style={{ background: categoryColors[t.category] }}/>{t.category}</span><strong>{prettyMinutes(t.minutes)}</strong></div>)}</div></div>
      <div className="goal-card"><h2><Target size={17}/> 每日专注目标</h2><p className="muted help">学习与工作合计</p><div className="goal-value"><strong>{Math.floor(focus)}<small> / {data.goal} 分钟</small></strong><span>{data.goal ? `${Math.min(100,Math.round(focus/data.goal*100))}%` : '未设置'}</span></div><Progress value={data.goal ? Math.min(100,focus/data.goal*100) : 0} aria-label="每日专注目标完成度"/><label className="goal-setting">目标<input aria-label="每日目标分钟" type="number" min={0} max={1440} step={1} value={goalInput} onChange={e => setGoalInput(e.target.value)} onBlur={() => { const n = Number(goalInput); if (!goalInput || !Number.isInteger(n) || n<0 || n>1440) { setGoalInput(String(data.goal)); toast.error('目标应为 0–1440 的整数分钟。'); } else update(t => ({ ...t, goal: n })); }}/><span>分钟</span></label></div>
      <div className="week-card"><h2>最近七天</h2><p className="muted help">截至所选日期 · 已记录时长</p><div className="week-chart">{week.map(d => <button key={d.day} onClick={() => setDay(d.day)} className={d.day === effectiveDay ? 'selected' : ''} title={`${d.day}：${prettyMinutes(d.value)}`}><span className="week-column"><i style={{ height: `${Math.max(3,d.value/weekMax*100)}%` }}/></span><span>{d.label}</span></button>)}</div></div><div className="backup-actions"><Button variant="ghost" onClick={backup}><Download size={15}/> 备份</Button><Button variant="ghost" onClick={() => { if (data.active) { toast.error('请先结束当前计时，再导入备份。'); return; } input.current?.click(); }}><Upload size={15}/> 恢复</Button><input ref={input} type="file" accept=".json,application/json" hidden onChange={e => void importFile(e.target.files?.[0])}/></div>
    </aside></div></fieldset>
    <Dialog open={!!form} onOpenChange={v => { if (!v) setForm(null); }}><DialogContent><DialogHeader><DialogTitle>{form?.id ? '编辑时间记录' : '补记一段时间'}</DialogTitle><DialogDescription>只记录已发生的时间，同一时段不会重复计算。</DialogDescription></DialogHeader>{form && <form onSubmit={saveForm} className="entry-form"><label className="field">事项<input autoFocus aria-label="补记事项" value={form.title} maxLength={160} onChange={e => setForm({ ...form, title: e.target.value })}/></label><label className="field">分类<Pick value={form.category} onChange={v => setForm({ ...form, category: v as Category })} label="补记分类" options={categories.map(c => ({ value: c, label: c }))}/></label><label className="field">开始<input aria-label="开始时间" type="datetime-local" required value={form.start} onChange={e => setForm({ ...form, start: e.target.value })}/></label><label className="field">结束<input aria-label="结束时间" type="datetime-local" required value={form.end} onChange={e => setForm({ ...form, end: e.target.value })}/></label>{formError && <p className="field-error" role="alert">{formError}</p>}<Button type="submit">保存记录</Button></form>}</DialogContent></Dialog>
    <Confirm open={!!removeId} onClose={() => setRemoveId(null)} title="删除这条时间记录？" description="该记录会从账本与每日统计中移除。" onConfirm={() => { update(t => ({ ...t, entries: t.entries.filter(e => e.id !== removeId) })); setRemoveId(null); }}/>
    <Confirm open={!!incoming} onClose={() => setIncoming(null)} title="恢复备份并替换账本？" description="现有记录会被替换，请先备份。备份中的未结束计时不会恢复。" onConfirm={() => { update(incoming!); setIncoming(null); toast.success('账本已恢复'); }}/>
  </section>;
}

